## DataCleaning and PreProcessing

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("OLA_DataSet.xlsx")
df

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103019,2024-07-31 09:06:00,09:06:00,CNR9488489435,Success,CID371654,Prime Plus,Richmond Town,Varthur,245.0,35.0,NaN,NaN,No,NaN,111,Cash,41,3.6,3.8,https://cdn-icons-png.flaticon.com/128/11409/1...
103020,2024-07-31 15:12:00,15:12:00,CNR3151743100,Success,CID334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,NaN,NaN,No,NaN,1097,UPI,17,4.3,3.3,https://cdn-icons-png.flaticon.com/128/16526/1...
103021,2024-07-31 13:59:00,13:59:00,CNR1286151233,Success,CID113188,Prime SUV,Bannerghatta Road,JP Nagar,35.0,75.0,NaN,NaN,No,NaN,2201,Cash,37,3.6,3.2,https://cdn-icons-png.flaticon.com/128/9983/99...
103022,2024-07-31 14:56:00,14:56:00,CNR2027162035,Success,CID118301,eBike,Indiranagar,Magadi Road,210.0,140.0,NaN,NaN,No,NaN,267,UPI,47,3.4,3.1,https://cdn-icons-png.flaticon.com/128/6839/68...
103023,2024-07-31 13:57:00,13:57:00,CNR9770709721,Success,CID217959,Auto,Ulsoor,Hennur,175.0,125.0,NaN,NaN,No,NaN,462,UPI,3,4.8,4.4,https://cdn-icons-png.flaticon.com/128/16526/1...

In [3]:
print(df.duplicated().sum()) # There is no duplicated values
print(df.shape)
df.isnull().sum().sort_values(ascending=False)

0
(103024, 20)

Incomplete_Rides_Reason       99098
Canceled_Rides_by_Customer    92525
Canceled_Rides_by_Driver      84590
Customer_Rating               39057
Driver_Ratings                39057
Payment_Method                39057
V_TAT                         39057
C_TAT                         39057
Incomplete_Rides              39057
Ride_Distance                     0
Booking_Value                     0
Date                              0
Time                              0
Drop_Location                     0
Pickup_Location                   0
Vehicle_Type                      0
Customer_ID                       0
Booking_Status                    0
Booking_ID                        0
Vehicle Images                    0
dtype: int64

In [4]:
df1 = df.drop(["Incomplete_Rides_Reason","Vehicle Images"],axis=1,inplace=False)

df1["Date"] = pd.to_datetime(df1["Date"], errors="coerce").dt.date
df1['Booking_ID'] = df1['Booking_ID'].str.extract('(\d+)') # will remove Variables
df1['Customer_ID'] = df1['Customer_ID'].str.extract('(\d+)')

df1

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating
0,2024-07-26,14:00:00,7153255142,Canceled by Driver,713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,444,NaN,0,NaN,NaN
1,2024-07-25,22:20:00,2940424040,Success,225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,158,Cash,13,4.1,4.0
2,2024-07-30,19:59:00,2982357879,Success,270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,386,UPI,40,4.2,4.8
3,2024-07-22,03:15:00,2395710036,Canceled by Customer,581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,384,NaN,0,NaN,NaN
4,2024-07-02,09:02:00,1797421769,Success,939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,822,Credit Card,45,4.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103019,2024-07-31,09:06:00,9488489435,Success,371654,Prime Plus,Richmond Town,Varthur,245.0,35.0,NaN,NaN,No,111,Cash,41,3.6,3.8
103020,2024-07-31,15:12:00,3151743100,Success,334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,NaN,NaN,No,1097,UPI,17,4.3,3.3
103021,2024-07-31,13:59:00,1286151233,Success,113188,Prime SUV,Bannerghatta Road,JP Nagar,35.0,75.0,NaN,NaN,No,2201,Cash,37,3.6,3.2
103022,2024-07-31,14:56:00,2027162035,Success,118301,eBike,Indiranagar,Magadi Road,210.0,140.0,NaN,NaN,No,267,UPI,47,3.4,3.1
103023,2024-07-31,13:57:00,9770709721,Success,217959,Auto,Ulsoor,Hennur,175.0,125.0,NaN,NaN,No,462,UPI,3,4.8,4.4

In [5]:
ride_volume = df1.groupby(df1["Date"]).size()
print(ride_volume.head())

Date
2024-07-01    3351
2024-07-02    3388
2024-07-03    3358
2024-07-04    3274
2024-07-05    3306
dtype: int64

In [6]:
df1.isnull().sum().sort_values(ascending=False)

Canceled_Rides_by_Customer    92525
Canceled_Rides_by_Driver      84590
C_TAT                         39057
V_TAT                         39057
Driver_Ratings                39057
Payment_Method                39057
Incomplete_Rides              39057
Customer_Rating               39057
Drop_Location                     0
Time                              0
Pickup_Location                   0
Vehicle_Type                      0
Customer_ID                       0
Booking_Value                     0
Booking_Status                    0
Ride_Distance                     0
Booking_ID                        0
Date                              0
dtype: int64

In [7]:
df1.describe()

,V_TAT,C_TAT,Booking_Value,Ride_Distance,Driver_Ratings,Customer_Rating
count,63967.000000,63967.000000,103024.000000,103024.000000,63967.000000,63967.000000
mean,170.876952,84.873372,548.751883,14.189927,3.997457,3.998313
std,80.803640,36.005100,536.541221,15.776270,0.576834,0.578957
min,35.000000,25.000000,100.000000,0.000000,3.000000,3.000000
25%,98.000000,55.000000,242.000000,0.000000,3.500000,3.500000
50%,168.000000,85.000000,386.000000,8.000000,4.000000,4.000000
75%,238.000000,115.000000,621.000000,26.000000,4.500000,4.500000
max,308.000000,145.000000,2999.000000,49.000000,5.000000,5.000000

In [8]:
df1["Driver_Ratings"] = df1["Driver_Ratings"].fillna(df1["Driver_Ratings"].mean().round(1))
df1["Customer_Rating"] = df1["Customer_Rating"].fillna(df1["Customer_Rating"].mean().round(1))
df1["V_TAT"] = df1["V_TAT"].fillna(df1["V_TAT"].median())
df1["C_TAT"] = df1["C_TAT"].fillna(df1["C_TAT"].median())
df1["Ride_Distance"] = df1["Ride_Distance"].fillna(df1["Ride_Distance"].median())
df1["Booking_Value"] = df1["Booking_Value"].fillna(df1["Booking_Value"].median())
df1["Incomplete_Rides"] = df1["Incomplete_Rides"].map({"Yes": 1, "No": 0}).fillna(0)
df1["Payment_Method"] = df1["Payment_Method"].fillna("Unknown")
df1["Canceled_Rides_by_Customer"] = df1["Canceled_Rides_by_Customer"].fillna("Unknown")
df1["Canceled_Rides_by_Driver"] = df1["Canceled_Rides_by_Driver"].fillna("Unknown")

In [9]:
df1.isnull().sum() #Now i have the cleaned data

Date                          0
Time                          0
Booking_ID                    0
Booking_Status                0
Customer_ID                   0
Vehicle_Type                  0
Pickup_Location               0
Drop_Location                 0
V_TAT                         0
C_TAT                         0
Canceled_Rides_by_Customer    0
Canceled_Rides_by_Driver      0
Incomplete_Rides              0
Booking_Value                 0
Payment_Method                0
Ride_Distance                 0
Driver_Ratings                0
Customer_Rating               0
dtype: int64

In [10]:
df1

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating
0,2024-07-26,14:00:00,7153255142,Canceled by Driver,713523,Prime Sedan,Tumkur Road,RT Nagar,168.0,85.0,Unknown,Personal & Car related issue,0.0,444,Unknown,0,4.0,4.0
1,2024-07-25,22:20:00,2940424040,Success,225428,Bike,Magadi Road,Varthur,203.0,30.0,Unknown,Unknown,0.0,158,Cash,13,4.1,4.0
2,2024-07-30,19:59:00,2982357879,Success,270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,Unknown,Unknown,0.0,386,UPI,40,4.2,4.8
3,2024-07-22,03:15:00,2395710036,Canceled by Customer,581320,eBike,HSR Layout,Vijayanagar,168.0,85.0,Driver is not moving towards pickup location,Unknown,0.0,384,Unknown,0,4.0,4.0
4,2024-07-02,09:02:00,1797421769,Success,939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,Unknown,Unknown,0.0,822,Credit Card,45,4.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103019,2024-07-31,09:06:00,9488489435,Success,371654,Prime Plus,Richmond Town,Varthur,245.0,35.0,Unknown,Unknown,0.0,111,Cash,41,3.6,3.8
103020,2024-07-31,15:12:00,3151743100,Success,334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,Unknown,Unknown,0.0,1097,UPI,17,4.3,3.3
103021,2024-07-31,13:59:00,1286151233,Success,113188,Prime SUV,Bannerghatta Road,JP Nagar,35.0,75.0,Unknown,Unknown,0.0,2201,Cash,37,3.6,3.2
103022,2024-07-31,14:56:00,2027162035,Success,118301,eBike,Indiranagar,Magadi Road,210.0,140.0,Unknown,Unknown,0.0,267,UPI,47,3.4,3.1
103023,2024-07-31,13:57:00,9770709721,Success,217959,Auto,Ulsoor,Hennur,175.0,125.0,Unknown,Unknown,0.0,462,UPI,3,4.8,4.4

In [11]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 18 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  object
 1   Time                        103024 non-null  object
 2   Booking_ID                  103024 non-null  object
 3   Booking_Status              103024 non-null  object
 4   Customer_ID                 103024 non-null  object
 5   Vehicle_Type                103024 non-null  object
 6   Pickup_Location             103024 non-null  object
 7   Drop_Location               103024 non-null  object
 8   V_TAT                       103024 non-null  float64
 9   C_TAT                       103024 non-null  float64
 10  Canceled_Rides_by_Customer  103024 non-null  object
 11  Canceled_Rides_by_Driver    103024 non-null  object
 12  Incomplete_Rides            103024 non-null  float64
 13  Booking_Value               103024 non-null  int64
 14  Payment_Method              103024 non-null  object
 15  Ride_Distance               103024 non-null  int64
 16  Driver_Ratings              103024 non-null  float64
 17  Customer_Rating             103024 non-null  float64
dtypes: float64(5), int64(2), object(11)
memory usage: 14.1+ MB

### Encoding

In [12]:
print(df1["Pickup_Location"].unique()) # Nominal Data - one hot encoding
print("---------------------------------")
print(df1["Drop_Location"].unique()) # Nominal Data - one hot encoding
print("---------------------------------")

['Tumkur Road' 'Magadi Road' 'Sahakar Nagar' 'HSR Layout' 'Rajajinagar'
 'Kadugodi' 'Bannerghatta Road' 'Chamarajpet' 'RT Nagar' 'Hosur Road'
 'Kammanahalli' 'Cox Town' 'Indiranagar' 'Ramamurthy Nagar'
 'Electronic City' 'Koramangala' 'Basavanagudi' 'Padmanabhanagar'
 'Mysore Road' 'Yelahanka' 'Frazer Town' 'Jayanagar' 'Majestic'
 'Yeshwanthpur' 'Peenya' 'Marathahalli' 'KR Puram' 'Hulimavu'
 'Shivajinagar' 'Hennur' 'Devanahalli' 'Rajarajeshwari Nagar' 'Ulsoor'
 'Shantinagar' 'JP Nagar' 'Chickpet' 'Langford Town' 'BTM Layout'
 'Sarjapur Road' 'Bellandur' 'Richmond Town' 'Kengeri' 'Banashankari'
 'Vijayanagar' 'Malleshwaram' 'Whitefield' 'MG Road' 'Hebbal' 'Nagarbhavi'
 'Varthur']
---------------------------------
['RT Nagar' 'Varthur' 'Vijayanagar' 'Chamarajpet' 'Whitefield'
 'Sarjapur Road' 'Peenya' 'Jayanagar' 'Rajajinagar' 'Yelahanka'
 'Banashankari' 'MG Road' 'HSR Layout' 'BTM Layout' 'Langford Town'
 'Hulimavu' 'Sahakar Nagar' 'Koramangala' 'Hennur' 'Malleshwaram'
 'Indiranagar' 'Richmond Town' 'Hosur Road' 'JP Nagar' 'Yeshwanthpur'
 'Rajarajeshwari Nagar' 'Majestic' 'Kengeri' 'Mysore Road' 'Shivajinagar'
 'Marathahalli' 'Magadi Road' 'Padmanabhanagar' 'Chickpet' 'Kadugodi'
 'Basavanagudi' 'Nagarbhavi' 'Kammanahalli' 'Frazer Town' 'Shantinagar'
 'Bannerghatta Road' 'Devanahalli' 'Ramamurthy Nagar' 'Cox Town'
 'Electronic City' 'Bellandur' 'KR Puram' 'Tumkur Road' 'Hebbal' 'Ulsoor']
---------------------------------

In [13]:
print(df1["Vehicle_Type"].unique()) # Nominal Data - one hot encoding
print("---------------------------------")
print(df1["Booking_Status"].unique()) # nominal encoding
print("---------------------------------")
print(df1["Canceled_Rides_by_Customer"].unique()) # Nominal Data - one hot encoding
print("---------------------------------")
print(df1["Canceled_Rides_by_Driver"].unique()) # Nominal Data 
print("---------------------------------")
print(df1["Payment_Method"].unique()) # Nominal data

['Prime Sedan' 'Bike' 'Prime SUV' 'eBike' 'Mini' 'Prime Plus' 'Auto']
---------------------------------
['Canceled by Driver' 'Success' 'Canceled by Customer' 'Driver Not Found']
---------------------------------
['Unknown' 'Driver is not moving towards pickup location'
 'Driver asked to cancel' 'AC is Not working' 'Change of plans'
 'Wrong Address']
---------------------------------
['Personal & Car related issue' 'Unknown' 'Customer was coughing/sick'
 'Customer related issue' 'More than permitted people in there']
---------------------------------
['Unknown' 'Cash' 'UPI' 'Credit Card' 'Debit Card']

In [14]:
df_encoded = pd.get_dummies(df1, columns=[
                                        "Pickup_Location",
                                        "Drop_Location",
                                        "Vehicle_Type",
                                        "Booking_Status", 
                                        "Canceled_Rides_by_Customer",
                                        "Canceled_Rides_by_Driver",
                                        "Payment_Method"], dtype="int")
df_encoded

,Date,Time,Booking_ID,Customer_ID,V_TAT,C_TAT,Incomplete_Rides,Booking_Value,Ride_Distance,Driver_Ratings,...,Canceled_Rides_by_Driver_Customer related issue,Canceled_Rides_by_Driver_Customer was coughing/sick,Canceled_Rides_by_Driver_More than permitted people in there,Canceled_Rides_by_Driver_Personal & Car related issue,Canceled_Rides_by_Driver_Unknown,Payment_Method_Cash,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_UPI,Payment_Method_Unknown
0,2024-07-26,14:00:00,7153255142,713523,168.0,85.0,0.0,444,0,4.0,...,0,0,0,1,0,0,0,0,0,1
1,2024-07-25,22:20:00,2940424040,225428,203.0,30.0,0.0,158,13,4.1,...,0,0,0,0,1,1,0,0,0,0
2,2024-07-30,19:59:00,2982357879,270156,238.0,130.0,0.0,386,40,4.2,...,0,0,0,0,1,0,0,0,1,0
3,2024-07-22,03:15:00,2395710036,581320,168.0,85.0,0.0,384,0,4.0,...,0,0,0,0,1,0,0,0,0,1
4,2024-07-02,09:02:00,1797421769,939555,252.0,80.0,0.0,822,45,4.0,...,0,0,0,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103019,2024-07-31,09:06:00,9488489435,371654,245.0,35.0,0.0,111,41,3.6,...,0,0,0,0,1,1,0,0,0,0
103020,2024-07-31,15:12:00,3151743100,334158,84.0,145.0,0.0,1097,17,4.3,...,0,0,0,0,1,0,0,0,1,0
103021,2024-07-31,13:59:00,1286151233,113188,35.0,75.0,0.0,2201,37,3.6,...,0,0,0,0,1,1,0,0,0,0
103022,2024-07-31,14:56:00,2027162035,118301,210.0,140.0,0.0,267,47,3.4,...,0,0,0,0,1,0,0,0,1,0
103023,2024-07-31,13:57:00,9770709721,217959,175.0,125.0,0.0,462,3,4.8,...,0,0,0,0,1,0,0,0,1,0

In [15]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Columns: 138 entries, Date to Payment_Method_Unknown
dtypes: float64(5), int64(129), object(4)
memory usage: 108.5+ MB

### Saving as New CSV data

In [16]:
df1.to_csv("F:\GUVI_Class\GUVI_Class_Code\OLA_Project\Cleaned_OLA_Datasheet.csv")

In [17]:
df_encoded.to_csv("F:\GUVI_Class\GUVI_Class_Code\OLA_Project\Encoded_OLA_Datasheet.csv")

In [18]:
df1.isnull().sum()

Date                          0
Time                          0
Booking_ID                    0
Booking_Status                0
Customer_ID                   0
Vehicle_Type                  0
Pickup_Location               0
Drop_Location                 0
V_TAT                         0
C_TAT                         0
Canceled_Rides_by_Customer    0
Canceled_Rides_by_Driver      0
Incomplete_Rides              0
Booking_Value                 0
Payment_Method                0
Ride_Distance                 0
Driver_Ratings                0
Customer_Rating               0
dtype: int64

In [19]:
df_encoded.isnull().sum()

Date                          0
Time                          0
Booking_ID                    0
Customer_ID                   0
V_TAT                         0
                             ..
Payment_Method_Cash           0
Payment_Method_Credit Card    0
Payment_Method_Debit Card     0
Payment_Method_UPI            0
Payment_Method_Unknown        0
Length: 138, dtype: int64

In [20]:
df1.keys()

Index(['Date', 'Time', 'Booking_ID', 'Booking_Status', 'Customer_ID',
       'Vehicle_Type', 'Pickup_Location', 'Drop_Location', 'V_TAT', 'C_TAT',
       'Canceled_Rides_by_Customer', 'Canceled_Rides_by_Driver',
       'Incomplete_Rides', 'Booking_Value', 'Payment_Method', 'Ride_Distance',
       'Driver_Ratings', 'Customer_Rating'],
      dtype='object')