### SQL Analysis

In [1]:
import pandas as pd

df = pd.read_csv("Cleaned_OLA_Datasheet.csv")
df

,Unnamed: 0,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating
0,0,2024-07-26,14:00:00,7153255142,Canceled by Driver,713523,Prime Sedan,Tumkur Road,RT Nagar,168.0,85.0,Unknown,Personal & Car related issue,0.0,444,Unknown,0,4.0,4.0
1,1,2024-07-25,22:20:00,2940424040,Success,225428,Bike,Magadi Road,Varthur,203.0,30.0,Unknown,Unknown,0.0,158,Cash,13,4.1,4.0
2,2,2024-07-30,19:59:00,2982357879,Success,270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,Unknown,Unknown,0.0,386,UPI,40,4.2,4.8
3,3,2024-07-22,03:15:00,2395710036,Canceled by Customer,581320,eBike,HSR Layout,Vijayanagar,168.0,85.0,Driver is not moving towards pickup location,Unknown,0.0,384,Unknown,0,4.0,4.0
4,4,2024-07-02,09:02:00,1797421769,Success,939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,Unknown,Unknown,0.0,822,Credit Card,45,4.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103019,103019,2024-07-31,09:06:00,9488489435,Success,371654,Prime Plus,Richmond Town,Varthur,245.0,35.0,Unknown,Unknown,0.0,111,Cash,41,3.6,3.8
103020,103020,2024-07-31,15:12:00,3151743100,Success,334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,Unknown,Unknown,0.0,1097,UPI,17,4.3,3.3
103021,103021,2024-07-31,13:59:00,1286151233,Success,113188,Prime SUV,Bannerghatta Road,JP Nagar,35.0,75.0,Unknown,Unknown,0.0,2201,Cash,37,3.6,3.2
103022,103022,2024-07-31,14:56:00,2027162035,Success,118301,eBike,Indiranagar,Magadi Road,210.0,140.0,Unknown,Unknown,0.0,267,UPI,47,3.4,3.1
103023,103023,2024-07-31,13:57:00,9770709721,Success,217959,Auto,Ulsoor,Hennur,175.0,125.0,Unknown,Unknown,0.0,462,UPI,3,4.8,4.4

In [2]:
df.isnull().sum()

Unnamed: 0                    0
Date                          0
Time                          0
Booking_ID                    0
Booking_Status                0
Customer_ID                   0
Vehicle_Type                  0
Pickup_Location               0
Drop_Location                 0
V_TAT                         0
C_TAT                         0
Canceled_Rides_by_Customer    0
Canceled_Rides_by_Driver      0
Incomplete_Rides              0
Booking_Value                 0
Payment_Method                0
Ride_Distance                 0
Driver_Ratings                0
Customer_Rating               0
dtype: int64

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 19 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Unnamed: 0                  103024 non-null  int64
 1   Date                        103024 non-null  object
 2   Time                        103024 non-null  object
 3   Booking_ID                  103024 non-null  int64
 4   Booking_Status              103024 non-null  object
 5   Customer_ID                 103024 non-null  int64
 6   Vehicle_Type                103024 non-null  object
 7   Pickup_Location             103024 non-null  object
 8   Drop_Location               103024 non-null  object
 9   V_TAT                       103024 non-null  float64
 10  C_TAT                       103024 non-null  float64
 11  Canceled_Rides_by_Customer  103024 non-null  object
 12  Canceled_Rides_by_Driver    103024 non-null  object
 13  Incomplete_Rides            103024 non-null  float64
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              103024 non-null  object
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              103024 non-null  float64
 18  Customer_Rating             103024 non-null  float64
dtypes: float64(5), int64(5), object(9)
memory usage: 14.9+ MB

In [4]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:12345678@localhost:3306/ola_db")
df.to_sql(
            name = "ola_analysis",
            con = engine,
            if_exists = "replace",
            index = False,
            )

103024

In [5]:
query = """ DESCRIBE
                    ola_analysis"""

df0 = pd.read_sql(query,engine)
df0

                         Field    Type Null Key Default Extra
0                   Unnamed: 0  bigint  YES        None
1                         Date    text  YES        None
2                         Time    text  YES        None
3                   Booking_ID  bigint  YES        None
4               Booking_Status    text  YES        None
5                  Customer_ID  bigint  YES        None
6                 Vehicle_Type    text  YES        None
7              Pickup_Location    text  YES        None
8                Drop_Location    text  YES        None
9                        V_TAT  double  YES        None
10                       C_TAT  double  YES        None
11  Canceled_Rides_by_Customer    text  YES        None
12    Canceled_Rides_by_Driver    text  YES        None
13            Incomplete_Rides  double  YES        None
14               Booking_Value  bigint  YES        None
15              Payment_Method    text  YES        None
16               Ride_Distance  bigint  YES        None
17              Driver_Ratings  double  YES        None
18             Customer_Rating  double  YES        None

SELECT   -> Choose the columns
  |
FROM     -> Choose from the Table
  |
WHERE    -> Filter the rows(specific)
  |
GROUP BY -> Group data
  |
HAVING   -> Filter grouped data
  |
ORDER BY -> Sort results
  |
LIMIT    -> show the data as per the limit num

##  Retrieve all successful bookings:

In [6]:
df["Booking_Status"].value_counts()

Booking_Status
Success                 63967
Canceled by Driver      18434
Canceled by Customer    10499
Driver Not Found        10124
Name: count, dtype: int64

In [7]:
query = """
SELECT
    Booking_Status,
    COUNT(*) AS booking_counts
FROM
    ola_analysis
WHERE
    Booking_Status = 'Success'
"""

df1 = pd.read_sql(query, engine)
df1

  Booking_Status  booking_counts
0        Success           63967

## Find the average ride distance for each vehicle type:

In [8]:
query = """
SELECT
    Vehicle_Type,
    AVG(Ride_Distance) AS avg_dist,
    COUNT(*) AS count
FROM
    ola_analysis
GROUP BY
    Vehicle_Type
"""

df2 = pd.read_sql(query, engine)
df2

  Vehicle_Type  avg_dist  count
0  Prime Sedan   15.7649  14877
1         Bike   15.5331  14662
2    Prime SUV   15.2745  14655
3        eBike   15.5806  14816
4         Mini   15.5101  14552
5   Prime Plus   15.4475  14707
6         Auto    6.2381  14755

## Get the total number of cancelled rides by customers:

In [9]:
df["Canceled_Rides_by_Customer"].value_counts()

Canceled_Rides_by_Customer
Unknown                                         92525
Driver is not moving towards pickup location     3175
Driver asked to cancel                           2670
Change of plans                                  2081
AC is Not working                                1568
Wrong Address                                    1005
Name: count, dtype: int64

In [10]:
query = """
SELECT 
    COUNT(*) AS total_cancelled_by_customer
FROM
    ola_analysis
WHERE
    Canceled_Rides_by_Customer != 'Unknown'
"""

df3 = pd.read_sql(query, engine)
df3

   total_cancelled_by_customer
0                        10499

##  Get the number of rides cancelled by drivers due to personal and car-related issue

In [11]:
df["Canceled_Rides_by_Driver"].value_counts()

Canceled_Rides_by_Driver
Unknown                                84590
Personal & Car related issue            6542
Customer related issue                  5413
Customer was coughing/sick              3654
More than permitted people in there     2825
Name: count, dtype: int64

In [12]:
query = """ 
SELECT
    Canceled_Rides_by_Driver,
    COUNT(*) AS total_count
FROM 
    ola_analysis
WHERE
    Canceled_Rides_by_Driver = "Personal & Car related issue"
"""

df4 = pd.read_sql(query, engine)
df4

       Canceled_Rides_by_Driver  total_count
0  Personal & Car related issue         6542

##  Find the maximum and minimum driver ratings for Prime Sedan bookings

In [13]:
df["Vehicle_Type"].value_counts()

Vehicle_Type
Prime Sedan    14877
eBike          14816
Auto           14755
Prime Plus     14707
Bike           14662
Prime SUV      14655
Mini           14552
Name: count, dtype: int64

In [14]:
query = """
SELECT 
    Vehicle_Type,
    COUNT(*) AS Count,
    MAX(Driver_Ratings) AS max_driver_rating,
    MIN(Driver_Ratings) AS min_driver_rating
FROM
    ola_analysis
WHERE
    Vehicle_Type = 'Prime Sedan'
"""

df5 = pd.read_sql(query, engine)
df5

  Vehicle_Type  Count  max_driver_rating  min_driver_rating
0  Prime Sedan  14877                5.0                3.0

##  Retrieve all rides where payment was made using UPI:

In [15]:
df["Payment_Method"].value_counts()

Payment_Method
Unknown        39057
Cash           35022
UPI            25881
Credit Card     2435
Debit Card       629
Name: count, dtype: int64

In [16]:
query = """ 
SELECT
    Payment_Method,
    COUNT(*) AS total_count
FROM 
    ola_analysis
WHERE
    Payment_Method = "UPI"
"""

df6 = pd.read_sql(query, engine)
df6

  Payment_Method  total_count
0            UPI        25881

##  Find the average customer rating per vehicle type:

In [17]:
query = """
SELECT 
    Vehicle_Type,
    AVG(Customer_Rating) AS average_customer_rating
FROM
    ola_analysis
GROUP BY
    Vehicle_Type
ORDER BY
    average_customer_rating DESC
"""

df7 = pd.read_sql(query, engine)
df7

  Vehicle_Type  average_customer_rating
0   Prime Plus                 4.005861
1  Prime Sedan                 4.001002
2    Prime SUV                 3.999618
3         Auto                 3.999261
4         Mini                 3.998591
5         Bike                 3.995874
6        eBike                 3.992474

## Calculate the total booking value of rides completed successfully:

In [18]:
df["Booking_Status"].value_counts()

Booking_Status
Success                 63967
Canceled by Driver      18434
Canceled by Customer    10499
Driver Not Found        10124
Name: count, dtype: int64

In [19]:
query = """ 
SELECT
    Booking_Status,
    COUNT(*) AS total_count
FROM 
    ola_analysis
WHERE
    Booking_Status = "Success"
"""

df8 = pd.read_sql(query, engine)
df8

  Booking_Status  total_count
0        Success        63967

## List all incomplete rides along with the reason

In [20]:
df["Incomplete_Rides"].value_counts()

Incomplete_Rides
0.0    99098
1.0     3926
Name: count, dtype: int64

In [21]:
query = """ 
SELECT
    Incomplete_Rides,
    COUNT(*) AS total_count
FROM 
    ola_analysis
WHERE
    Incomplete_Rides = 0.0
"""

df9 = pd.read_sql(query, engine)
df9

   Incomplete_Rides  total_count
0               0.0        99098

In [22]:
df.keys()

Index(['Unnamed: 0', 'Date', 'Time', 'Booking_ID', 'Booking_Status',
       'Customer_ID', 'Vehicle_Type', 'Pickup_Location', 'Drop_Location',
       'V_TAT', 'C_TAT', 'Canceled_Rides_by_Customer',
       'Canceled_Rides_by_Driver', 'Incomplete_Rides', 'Booking_Value',
       'Payment_Method', 'Ride_Distance', 'Driver_Ratings', 'Customer_Rating'],
      dtype='object')

In [23]:
df

,Unnamed: 0,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating
0,0,2024-07-26,14:00:00,7153255142,Canceled by Driver,713523,Prime Sedan,Tumkur Road,RT Nagar,168.0,85.0,Unknown,Personal & Car related issue,0.0,444,Unknown,0,4.0,4.0
1,1,2024-07-25,22:20:00,2940424040,Success,225428,Bike,Magadi Road,Varthur,203.0,30.0,Unknown,Unknown,0.0,158,Cash,13,4.1,4.0
2,2,2024-07-30,19:59:00,2982357879,Success,270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,Unknown,Unknown,0.0,386,UPI,40,4.2,4.8
3,3,2024-07-22,03:15:00,2395710036,Canceled by Customer,581320,eBike,HSR Layout,Vijayanagar,168.0,85.0,Driver is not moving towards pickup location,Unknown,0.0,384,Unknown,0,4.0,4.0
4,4,2024-07-02,09:02:00,1797421769,Success,939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,Unknown,Unknown,0.0,822,Credit Card,45,4.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103019,103019,2024-07-31,09:06:00,9488489435,Success,371654,Prime Plus,Richmond Town,Varthur,245.0,35.0,Unknown,Unknown,0.0,111,Cash,41,3.6,3.8
103020,103020,2024-07-31,15:12:00,3151743100,Success,334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,Unknown,Unknown,0.0,1097,UPI,17,4.3,3.3
103021,103021,2024-07-31,13:59:00,1286151233,Success,113188,Prime SUV,Bannerghatta Road,JP Nagar,35.0,75.0,Unknown,Unknown,0.0,2201,Cash,37,3.6,3.2
103022,103022,2024-07-31,14:56:00,2027162035,Success,118301,eBike,Indiranagar,Magadi Road,210.0,140.0,Unknown,Unknown,0.0,267,UPI,47,3.4,3.1
103023,103023,2024-07-31,13:57:00,9770709721,Success,217959,Auto,Ulsoor,Hennur,175.0,125.0,Unknown,Unknown,0.0,462,UPI,3,4.8,4.4